### ISSUE TITLE
use glide load picture problem 

### ISSUE THREAD

**Issue by t2314862168** [yayaa/ParallaxRecyclerView#1]
@yayaa 
I use Glide to test the library,then i find a problem . If  the finger don't move in the screen , the screenshots is this 
![qq 20160309155928](https://cloud.githubusercontent.com/assets/6425339/13628805/0e4568f2-e610-11e5-931a-a56a5a5f1e73.png)
the pictures do not display nomally. But if the finger move in the screen ,the screenshots is this 
![qq 20160309155959](https://cloud.githubusercontent.com/assets/6425339/13628829/34e25c22-e610-11e5-958f-ddae3310a0ca.png)
the pictures can display nomally
my code is below 

``` java
 @Override
    public void onBindViewHolder(ViewHolder viewHolder, int position) {
        MyGlideUtils.loadImgByResId(context, imageIds[position % imageIds.length], viewHolder.getBackgroundImage());
//        viewHolder.getBackgroundImage().setImageResource(imageIds[position % imageIds.length]);
        viewHolder.getTextView().setText("Row " + position);

        // # CAUTION:
        // Important to call this method
        viewHolder.getBackgroundImage().reuse();
    }
```

MyGlideUtils is below

``` java
public static void loadImgByResId(Context context, int resId, ImageView imageView) {
        Glide.with(context)
                .load(resId)
//                .centerCrop()
                .placeholder(R.mipmap.ic_launcher)
                .into(imageView);
    }
```

if use centerCrop the Parallax does't work ,the reason i don't find .
If you have free time , please help me ,thank you !

**Comment by yayaa** [comment]
Try to call parallaxImageView.reuse() before your Glide display method...
[See also](https://github.com/yayaa/ParallaxRecyclerView/blob/master/library/app/src/main/java/com/yayandroid/parallaxrecyclerview/ParallaxImageView.java#L54)
