### ISSUE TITLE
Picasso Placeholder issue

### ISSUE THREAD

**Issue by sunnykinger** [yayaa/ParallaxRecyclerView#3]
When I use a placeholder with Picasso then it acts weird. It loads the image in a tiny box at the top left corner over the placeholder and when I try and scroll, then the image immediately replaces the placeholder.

**Comment by yayaa** [comment]
Library uses images as Matrix scaleType not in centerCrop that's why. I would suggest you to set a listener to your Picasso implementation and try to call reuse on image when it's downloaded once. 
This is not an issue, it's about how you implement the library. So i'm closing this one.
