### ISSUE TITLE
i user your code in china 

### ISSUE THREAD

**Issue by daimaXZ** [yayaa/ParallaxRecyclerView#4]
this is my github address：https://github.com/daimaXZ/sicooDemo
The effect is so good，and it  would be popular in China  if you don't mind。
Thank you for your open source 。

**Comment by yayaa** [comment]
Cool :) That's why it is opensource, good luck!
But having mentioned my name would be nice though :)

**Comment by yayaa** [comment]
Consider using it as library, instead of copy & paste the code @daimaXZ
