### ISSUE TITLE
Image scale small

### ISSUE THREAD

**Issue by zentechthaingo** [yayaa/ParallaxRecyclerView#7]
I use your library for my RecyclerView. But some it load image small than real size of ParalaxImageView like this picture. I don't know why reason it happen. Sometime I reload RecycleView It happen. 
![screenshot 05-09-2016 22-42-20](https://cloud.githubusercontent.com/assets/14228312/18252811/bc43c8e4-73ba-11e6-9338-1dc4636ad5f3.png)

**Comment by yayaa** [comment]
Please see this threads: https://github.com/yayaa/ParallaxRecyclerView/issues/1 https://github.com/yayaa/ParallaxRecyclerView/issues/2 https://github.com/yayaa/ParallaxRecyclerView/issues/3

**Comment by zentechthaingo** [comment]
Thank yayaa I solved this problem !
